server:
  port: 9090
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

database:
  host: localhost
  port: 5432
  user: anvar
  password: ""
  dbname: subscriptions
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

logger:
  level: info
  format: json
